import {
  axieClass,
  parts,
  type,
} from './constants';
import {v4 as uuidv4} from 'uuid'

export const cards = [
  /**
   * horns
   */
  {
    id: uuidv4(),
    name: 'anemone',
    imgURL: 'cards/horn/anemonehorn.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'antenna',
    imgURL: 'cards/horn/antenna.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'arco',
    imgURL: 'cards/horn/arco.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'babylonia',
    imgURL: 'cards/horn/babylonia.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'bamboo shoot',
    imgURL: 'cards/horn/bambooshoot.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'beech',
    imgURL: 'cards/horn/beech.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'bumpy',
    imgURL: 'cards/horn/bumpy.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [
      type.POWER,
      type.INNATE,
    ],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'cactus',
    imgURL: 'cards/horn/cactus.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'caterpillars',
    imgURL: 'cards/horn/caterpillars.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cerastes',
    imgURL: 'cards/horn/cerastes.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'clamshell',
    imgURL: 'cards/horn/clamshell.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cuckoo',
    imgURL: 'cards/horn/cuckoo.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'dual blade',
    imgURL: 'cards/horn/dualblade.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'eggshell',
    imgURL: 'cards/horn/eggshell.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'feather spear',
    imgURL: 'cards/horn/featherspear.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'imp',
    imgURL: 'cards/horn/imp.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'incisor',
    imgURL: 'cards/horn/incisor.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'kestrel',
    imgURL: 'cards/horn/kestrel.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'lagging',
    imgURL: 'cards/horn/lagging.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'leaf bug',
    imgURL: 'cards/horn/leafbughorn.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'little branch',
    imgURL: 'cards/horn/littlebranch.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'merry',
    imgURL: 'cards/horn/merry.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'oranda',
    imgURL: 'cards/horn/oranda.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'parasite',
    imgURL: 'cards/horn/parasite.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pliers',
    imgURL: 'cards/horn/pliers.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pocky',
    imgURL: 'cards/horn/pocky.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'rose bud',
    imgURL: 'cards/horn/rosebud.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'scaly spear',
    imgURL: 'cards/horn/scalyspear.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'scaly spoon',
    imgURL: 'cards/horn/scalyspoon.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'shoal star',
    imgURL: 'cards/horn/shoalstar.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'strawberry shortcake',
    imgURL: 'cards/horn/strawberryshortcake.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'teal shell',
    imgURL: 'cards/horn/tealshell.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'trump',
    imgURL: 'cards/horn/trump.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'unko',
    imgURL: 'cards/horn/unko.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'watermelon',
    imgURL: 'cards/horn/watermelon.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'wing horn',
    imgURL: 'cards/horn/winghorn.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },

  /**
   * mouths
   */
  {
    id: uuidv4(),
    name: 'axie kiss',
    imgURL: 'cards/mouth/axiekiss.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'catfish',
    imgURL: 'cards/mouth/catfish.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'confident',
    imgURL: 'cards/mouth/confident.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'cute bunny',
    imgURL: 'cards/mouth/cutebunny.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'doubletalk',
    imgURL: 'cards/mouth/doubletalk.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'goda',
    imgURL: 'cards/mouth/goda.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [
      type.ATTACK,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'herbivore',
    imgURL: 'cards/mouth/herbivore.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hungry bird',
    imgURL: 'cards/mouth/hungrybird.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'kotaro',
    imgURL: 'cards/mouth/kotaromouth.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'lam',
    imgURL: 'cards/mouth/lam.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'litte owl',
    imgURL: 'cards/mouth/littleowlmouth.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'mosquito',
    imgURL: 'cards/mouth/mosquito.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'nut cracker',
    imgURL: 'cards/mouth/nutcrackermouth.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'peace maker',
    imgURL: 'cards/mouth/peacemaker.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pincer',
    imgURL: 'cards/mouth/pincer.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'piranha',
    imgURL: 'cards/mouth/piranha.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'razor bite',
    imgURL: 'cards/mouth/razorbite.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'risky fish',
    imgURL: 'cards/mouth/riskyfish.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'serious',
    imgURL: 'cards/mouth/serious.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'silence whisper',
    imgURL: 'cards/mouth/silencewhisper.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'square teeth',
    imgURL: 'cards/mouth/squareteeth.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'tiny turtle',
    imgURL: 'cards/mouth/tinyturtle.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'toothless bite',
    imgURL: 'cards/mouth/toothlessbite.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'zigzag',
    imgURL: 'cards/mouth/zigzag.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },

  /**
   * backs
   */
  {
    id: uuidv4(),
    name: 'anemone',
    imgURL: 'cards/back/anemone.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'balloon',
    imgURL: 'cards/back/balloon.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'bidens',
    imgURL: 'cards/back/bidens.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'blue moon',
    imgURL: 'cards/back/bluemoon.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'bone sail',
    imgURL: 'cards/back/bonesail.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'buzz buzz',
    imgURL: 'cards/back/buzzbuzz.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'croc',
    imgURL: 'cards/back/croc.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cupid',
    imgURL: 'cards/back/cupid.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'furball',
    imgURL: 'cards/back/furball.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'garish worm',
    imgURL: 'cards/back/garishworm.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'goldfish',
    imgURL: 'cards/back/goldfish.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'green thorns',
    imgURL: 'cards/back/greenthorns.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hermit',
    imgURL: 'cards/back/hermit.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hero',
    imgURL: 'cards/back/hero.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'indian star',
    imgURL: 'cards/back/indianstar.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'jaguar',
    imgURL: 'cards/back/jaguar.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'kingfisher',
    imgURL: 'cards/back/kingfisher.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'mint',
    imgURL: 'cards/back/mint.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'perch',
    imgURL: 'cards/back/perch.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'pigeon post',
    imgURL: 'cards/back/pigeonpost.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pumpkin',
    imgURL: 'cards/back/pumpkin.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'raven',
    imgURL: 'cards/back/raven.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'red ear',
    imgURL: 'cards/back/redear.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'risky beast',
    imgURL: 'cards/back/riskybeast.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'ronin',
    imgURL: 'cards/back/ronin.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'sandal',
    imgURL: 'cards/back/sandal.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'scarab',
    imgURL: 'cards/back/scarab.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'shiitake',
    imgURL: 'cards/back/shiitake.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'snail shell',
    imgURL: 'cards/back/snailshell.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'spiky wing',
    imgURL: 'cards/back/spikywing.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'sponge',
    imgURL: 'cards/back/sponge.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'timber',
    imgURL: 'cards/back/timber.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tri feather',
    imgURL: 'cards/back/trifeather.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tri spikes',
    imgURL: 'cards/back/trispikes.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'turnip',
    imgURL: 'cards/back/turnip.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'watering can',
    imgURL: 'cards/back/wateringcan.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },

  /**
   * tails
   */
  {
    id: uuidv4(),
    name: 'ant',
    imgURL: 'cards/tail/ant.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'carrot',
    imgURL: 'cards/tail/carrot.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cattail;',
    imgURL: 'cards/tail/cattail.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cloud',
    imgURL: 'cards/tail/cloud.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cottontail',
    imgURL: 'cards/tail/cottontail.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'feather fan',
    imgURL: 'cards/tail/featherfan.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'fish snack',
    imgURL: 'cards/tail/fishsnack.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'gerbil',
    imgURL: 'cards/tail/gerbil.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'gila',
    imgURL: 'cards/tail/gila.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'granma\'s fan',
    imgURL: 'cards/tail/granmasfan.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [
      type.ATTACK,
      type.INNATE,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'grass snake',
    imgURL: 'cards/tail/grasssnake.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'gravel ant',
    imgURL: 'cards/tail/gravelant.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hare',
    imgURL: 'cards/tail/hare.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hatsune',
    imgURL: 'cards/tail/hatsune.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hotbutt',
    imgURL: 'cards/tail/hotbutt.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'iguana',
    imgURL: 'cards/tail/iguana.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'koi',
    imgURL: 'cards/tail/koi.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'navaga',
    imgURL: 'cards/tail/navaga.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'nimo',
    imgURL: 'cards/tail/nimo.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'nut cracker',
    imgURL: 'cards/tail/nutcrackertail.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'post fight',
    imgURL: 'cards/tail/postfight.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'potato leaf',
    imgURL: 'cards/tail/potatoleaf.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pupae',
    imgURL: 'cards/tail/pupae.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'ranchu',
    imgURL: 'cards/tail/ranchu.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'rice',
    imgURL: 'cards/tail/rice.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'shiba',
    imgURL: 'cards/tail/shiba.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'shrimp',
    imgURL: 'cards/tail/shrimp.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'snake jar',
    imgURL: 'cards/tail/snakejar.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'swallow',
    imgURL: 'cards/tail/swallow.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tadpole',
    imgURL: 'cards/tail/tadpole.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'the last one',
    imgURL: 'cards/tail/thelastone.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'thorny caterpillar',
    imgURL: 'cards/tail/thornycaterpillar.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tiny dino',
    imgURL: 'cards/tail/tinydino.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [
      type.ATTACK,
      type.RETAIN,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'twin tail',
    imgURL: 'cards/tail/twintail.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'wall gecko',
    imgURL: 'cards/tail/wallgecko.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'yam',
    imgURL: 'cards/tail/yam.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 0,
  },

  /**
   * ears
   */
  {
    id: uuidv4(),
    name: 'beetle spike',
    imgURL: 'cards/ear/beetlespike.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'belieber',
    imgURL: 'cards/ear/belieber.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'bubblemaker',
    imgURL: 'cards/ear/bubblemaker.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'clover',
    imgURL: 'cards/ear/clover.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'curly',
    imgURL: 'cards/ear/curly.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'curved spine',
    imgURL: 'cards/ear/curvedspine.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'ear breathing',
    imgURL: 'cards/ear/earbreathing.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'early bird',
    imgURL: 'cards/ear/earlybird.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'earwing',
    imgURL: 'cards/ear/earwing.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'friezard',
    imgURL: 'cards/ear/friezard.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'gill',
    imgURL: 'cards/ear/gill.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'hollow',
    imgURL: 'cards/ear/hollow.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'inkling',
    imgURL: 'cards/ear/inkling.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'innocent lamb',
    imgURL: 'cards/ear/innocentlamb.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'larva',
    imgURL: 'cards/ear/larva.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'leaf bug',
    imgURL: 'cards/ear/leafbugear.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'leafy',
    imgURL: 'cards/ear/leafy.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'little owl',
    imgURL: 'cards/ear/littleowlear.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'lotus',
    imgURL: 'cards/ear/lotus.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'nimo',
    imgURL: 'cards/ear/nimoear.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'nut craker',
    imgURL: 'cards/ear/nutcrackerear.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'nyan',
    imgURL: 'cards/ear/nyan.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pagona',
    imgURL: 'cards/ear/pagona.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'peace maker',
    imgURL: 'cards/ear/peacemakerear.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'pink cheek',
    imgURL: 'cards/ear/pinkcheek.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [
      type.SKILL,
      type.BANISH
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'puppy',
    imgURL: 'cards/ear/puppy.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'risky bird',
    imgURL: 'cards/ear/riskybird.png',
    class: axieClass.BIRD,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'rosa',
    imgURL: 'cards/ear/rosa.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [
      type.ATTACK,
      type.BANISH,
      type.INNATE,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'sakura',
    imgURL: 'cards/ear/sakura.png',
    class: axieClass.PLANT,
    part: parts.EAR,
    type: [type.POWER],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'seaslug',
    imgURL: 'cards/ear/seaslug.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'sidebarb',
    imgURL: 'cards/ear/sidebarb.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'small frill',
    imgURL: 'cards/ear/smallfrill.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'swirl',
    imgURL: 'cards/ear/swirl.png',
    class: axieClass.REPTILE,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tassels',
    imgURL: 'cards/ear/tassels.png',
    class: axieClass.BUG,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tiny fan',
    imgURL: 'cards/ear/tinyfan.png',
    class: axieClass.AQUATIC,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'zen',
    imgURL: 'cards/ear/zen.png',
    class: axieClass.BEAST,
    part: parts.EAR,
    type: [type.SKILL],
    energyCost: 1,
  },

  /**
   * eyes
   */
  {
    id: uuidv4(),
    name: 'blossom',
    imgURL: 'cards/eye/blossom.png',
    class: axieClass.PLANT,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'bookworm',
    imgURL: 'cards/eye/bookworm.png',
    class: axieClass.BUG,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'chubby',
    imgURL: 'cards/eye/chubby.png',
    class: axieClass.BEAST,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'clear',
    imgURL: 'cards/eye/clear.png',
    class: axieClass.AQUATIC,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'confusion',
    imgURL: 'cards/eye/confusion.png',
    class: axieClass.PLANT,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'cucumber slice',
    imgURL: 'cards/eye/cucumberslice.png',
    class: axieClass.PLANT,
    part: parts.EYE,
    type: [type.SKILL],
    energyCost: 2,
  },
  {
    id: uuidv4(),
    name: 'gecko',
    imgURL: 'cards/eye/gecko.png',
    class: axieClass.REPTILE,
    part: parts.EYE,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'gero',
    imgURL: 'cards/eye/gero.png',
    class: axieClass.AQUATIC,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'kotaro',
    imgURL: 'cards/eye/kotaroeyes.png',
    class: axieClass.BUG,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'little owl',
    imgURL: 'cards/eye/littleowleyes.png',
    class: axieClass.BIRD,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'little peas',
    imgURL: 'cards/eye/littlepeas.png',
    class: axieClass.BEAST,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'lucas',
    imgURL: 'cards/eye/lucas.png',
    class: axieClass.BIRD,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'mavis',
    imgURL: 'cards/eye/mavis.png',
    class: axieClass.BIRD,
    part: parts.EYE,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'neo',
    imgURL: 'cards/eye/neo.png',
    class: axieClass.BUG,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'nerdy',
    imgURL: 'cards/eye/nerdy.png',
    class: axieClass.BUG,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'papi',
    imgURL: 'cards/eye/papi.png',
    class: axieClass.PLANT,
    part: parts.EYE,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'puppy',
    imgURL: 'cards/eye/puppy.png',
    class: axieClass.BEAST,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'robin',
    imgURL: 'cards/eye/robin.png',
    class: axieClass.BIRD,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'scar',
    imgURL: 'cards/eye/scar.png',
    class: axieClass.REPTILE,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'sleepless',
    imgURL: 'cards/eye/sleepless.png',
    class: axieClass.AQUATIC,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'telescope',
    imgURL: 'cards/eye/telescope.png',
    class: axieClass.AQUATIC,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: uuidv4(),
    name: 'topaz',
    imgURL: 'cards/eye/topaz.png',
    class: axieClass.REPTILE,
    part: parts.EYE,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'tricky',
    imgURL: 'cards/eye/tricky.png',
    class: axieClass.REPTILE,
    part: parts.EYE,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: uuidv4(),
    name: 'zeal',
    imgURL: 'cards/eye/zeal.png',
    class: axieClass.BEAST,
    part: parts.EYE,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
];