import {
  axieClass,
  parts,
  type,
} from './constants';

export const cards = [
  /**
   * horns
   */
  {
    id: 1,
    name: 'anemone',
    imgURL: '/cards/horn/anemonehorn.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 2,
    name: 'antenna',
    imgURL: '/cards/horn/antenna.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: 3,
    name: 'arco',
    imgURL: '/cards/horn/arco.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 4,
    name: 'babylonia',
    imgURL: '/cards/horn/babylonia.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 5,
    name: 'bamboo shoot',
    imgURL: '/cards/horn/bambooshoot.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 6,
    name: 'beech',
    imgURL: '/cards/horn/beech.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 7,
    name: 'bumpy',
    imgURL: '/cards/horn/bumpy.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [
      type.POWER,
      type.INNATE,
    ],
    energyCost: 2,
  },
  {
    id: 8,
    name: 'cactus',
    imgURL: '/cards/horn/cactus.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 9,
    name: 'caterpillars',
    imgURL: '/cards/horn/caterpillars.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 10,
    name: 'cerastes',
    imgURL: '/cards/horn/cerastes.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 11,
    name: 'clamshell',
    imgURL: '/cards/horn/clamshell.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 12,
    name: 'cuckoo',
    imgURL: '/cards/horn/cuckoo.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 13,
    name: 'dual blade',
    imgURL: '/cards/horn/dualblade.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 14,
    name: 'eggshell',
    imgURL: '/cards/horn/eggshell.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 15,
    name: 'feather spear',
    imgURL: '/cards/horn/featherspear.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 16,
    name: 'imp',
    imgURL: '/cards/horn/imp.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 17,
    name: 'incisor',
    imgURL: '/cards/horn/incisor.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 18,
    name: 'kestrel',
    imgURL: '/cards/horn/kestrel.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 19,
    name: 'lagging',
    imgURL: '/cards/horn/lagging.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 20,
    name: 'leaf bug',
    imgURL: '/cards/horn/leafbughorn.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 21,
    name: 'little branch',
    imgURL: '/cards/horn/littlebranch.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 22,
    name: 'merry',
    imgURL: '/cards/horn/merry.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 23,
    name: 'oranda',
    imgURL: '/cards/horn/oranda.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 24,
    name: 'parasite',
    imgURL: '/cards/horn/parasite.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 25,
    name: 'pliers',
    imgURL: '/cards/horn/pliers.png',
    class: axieClass.BUG,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 26,
    name: 'pocky',
    imgURL: '/cards/horn/pocky.png',
    class: axieClass.BEAST,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 27,
    name: 'rose bud',
    imgURL: '/cards/horn/rosebud.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 28,
    name: 'scaly spear',
    imgURL: '/cards/horn/scalyspear.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 29,
    name: 'scaly spoon',
    imgURL: '/cards/horn/scalyspoon.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 30,
    name: 'shoal star',
    imgURL: '/cards/horn/shoalstar.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 31,
    name: 'strawberry shortcake',
    imgURL: '/cards/horn/strawberryshortcake.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 2,
  },
  {
    id: 32,
    name: 'teal shell',
    imgURL: '/cards/horn/tealshell.png',
    class: axieClass.AQUATIC,
    part: parts.HORN,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 33,
    name: 'trump',
    imgURL: '/cards/horn/trump.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 34,
    name: 'unko',
    imgURL: '/cards/horn/unko.png',
    class: axieClass.REPTILE,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 35,
    name: 'watermelon',
    imgURL: '/cards/horn/watermelon.png',
    class: axieClass.PLANT,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 36,
    name: 'wing horn',
    imgURL: '/cards/horn/winghorn.png',
    class: axieClass.BIRD,
    part: parts.HORN,
    type: [type.ATTACK],
    energyCost: 1,
  },

  /**
   * mouths
   */
  {
    id: 37,
    name: 'axie kiss',
    imgURL: '/cards/mouth/axiekiss.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 38,
    name: 'catfish',
    imgURL: '/cards/mouth/catfish.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 39,
    name: 'confident',
    imgURL: '/cards/mouth/confident.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.SKILL],
    energyCost: 0,
  },
  {
    id: 40,
    name: 'cute bunny',
    imgURL: '/cards/mouth/cutebunny.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 41,
    name: 'doubletalk',
    imgURL: '/cards/mouth/doubletalk.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 42,
    name: 'goda',
    imgURL: '/cards/mouth/goda.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [
      type.ATTACK,
      type.BANISH,
    ],
    energyCost: 1,
  },
  {
    id: 43,
    name: 'herbivore',
    imgURL: '/cards/mouth/herbivore.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 44,
    name: 'hungry bird',
    imgURL: '/cards/mouth/hungrybird.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 45,
    name: 'kotaro',
    imgURL: '/cards/mouth/kotaromouth.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 46,
    name: 'lam',
    imgURL: '/cards/mouth/lam.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 47,
    name: 'litte owl',
    imgURL: '/cards/mouth/littleowlmouth.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 48,
    name: 'mosquito',
    imgURL: '/cards/mouth/mosquito.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 49,
    name: 'nut cracker',
    imgURL: '/cards/mouth/nutcrackermouth.png',
    class: axieClass.BEAST,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 50,
    name: 'peace maker',
    imgURL: '/cards/mouth/peacemaker.png',
    class: axieClass.BIRD,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 51,
    name: 'pincer',
    imgURL: '/cards/mouth/pincer.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 52,
    name: 'piranha',
    imgURL: '/cards/mouth/piranha.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 53,
    name: 'razor bite',
    imgURL: '/cards/mouth/razorbite.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 54,
    name: 'risky fish',
    imgURL: '/cards/mouth/riskyfish.png',
    class: axieClass.AQUATIC,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 55,
    name: 'serious',
    imgURL: '/cards/mouth/serious.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 56,
    name: 'silence whisper',
    imgURL: '/cards/mouth/silencewhisper.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 57,
    name: 'square teeth',
    imgURL: '/cards/mouth/squareteeth.png',
    class: axieClass.BUG,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 0,
  },
  {
    id: 58,
    name: 'tiny turtle',
    imgURL: '/cards/mouth/tinyturtle.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 59,
    name: 'toothless bite',
    imgURL: '/cards/mouth/toothlessbite.png',
    class: axieClass.REPTILE,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 60,
    name: 'zigzag',
    imgURL: '/cards/mouth/zigzag.png',
    class: axieClass.PLANT,
    part: parts.MOUTH,
    type: [type.ATTACK],
    energyCost: 1,
  },

  /**
   * backs
   */
  {
    id: 61,
    name: 'anemone',
    imgURL: '/cards/back/anemone.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 62,
    name: 'balloon',
    imgURL: '/cards/back/balloon.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 63,
    name: 'bidens',
    imgURL: '/cards/back/bidens.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 64,
    name: 'blue moon',
    imgURL: '/cards/back/bluemoon.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 65,
    name: 'bone sail',
    imgURL: '/cards/back/bonesail.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 66,
    name: 'buzz buzz',
    imgURL: '/cards/back/buzzbuzz.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 67,
    name: 'croc',
    imgURL: '/cards/back/croc.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 68,
    name: 'cupid',
    imgURL: '/cards/back/cupid.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 69,
    name: 'furball',
    imgURL: '/cards/back/furball.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 70,
    name: 'garish worm',
    imgURL: '/cards/back/garishworm.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 71,
    name: 'goldfish',
    imgURL: '/cards/back/goldfish.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 72,
    name: 'green thorns',
    imgURL: '/cards/back/greenthorns.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 73,
    name: 'hermit',
    imgURL: '/cards/back/hermit.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 74,
    name: 'hero',
    imgURL: '/cards/back/hero.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 75,
    name: 'indian star',
    imgURL: '/cards/back/indianstar.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 76,
    name: 'jaguar',
    imgURL: '/cards/back/jaguar.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 77,
    name: 'kingfisher',
    imgURL: '/cards/back/kingfisher.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 78,
    name: 'mint',
    imgURL: '/cards/back/mint.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 79,
    name: 'perch',
    imgURL: '/cards/back/perch.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 80,
    name: 'pigeon post',
    imgURL: '/cards/back/pigeonpost.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 81,
    name: 'pumpkin',
    imgURL: '/cards/back/pumpkin.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 82,
    name: 'raven',
    imgURL: '/cards/back/raven.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 83,
    name: 'red ear',
    imgURL: '/cards/back/redear.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 84,
    name: 'risky beast',
    imgURL: '/cards/back/riskybeast.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 85,
    name: 'ronin',
    imgURL: '/cards/back/ronin.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 87,
    name: 'sandal',
    imgURL: '/cards/back/sandal.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 88,
    name: 'scarab',
    imgURL: '/cards/back/scarab.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 89,
    name: 'shiitake',
    imgURL: '/cards/back/shiitake.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 90,
    name: 'snail shell',
    imgURL: '/cards/back/snailshell.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 91,
    name: 'spiky wing',
    imgURL: '/cards/back/spikywing.png',
    class: axieClass.BUG,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 92,
    name: 'sponge',
    imgURL: '/cards/back/sponge.png',
    class: axieClass.AQUATIC,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 93,
    name: 'timber',
    imgURL: '/cards/back/timber.png',
    class: axieClass.BEAST,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 94,
    name: 'tri feather',
    imgURL: '/cards/back/trifeather.png',
    class: axieClass.BIRD,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 95,
    name: 'tri spikes',
    imgURL: '/cards/back/trispikes.png',
    class: axieClass.REPTILE,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 96,
    name: 'turnip',
    imgURL: '/cards/back/turnip.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 97,
    name: 'watering can',
    imgURL: '/cards/back/wateringcan.png',
    class: axieClass.PLANT,
    part: parts.BACK,
    type: [type.SECRET],
    energyCost: 1,
  },

  /**
   * tails
   */
  {
    id: 98,
    name: 'ant',
    imgURL: '/cards/tail/ant.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SKILL],
    energyCost: 1,
  },
  {
    id: 99,
    name: 'carrot',
    imgURL: '/cards/tail/carrot.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 100,
    name: 'cattail;',
    imgURL: '/cards/tail/cattail.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 101,
    name: 'cloud',
    imgURL: '/cards/tail/cloud.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 102,
    name: 'cottontail',
    imgURL: '/cards/tail/cottontail.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: 103,
    name: 'feather fan',
    imgURL: '/cards/tail/featherfan.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 104,
    name: 'fish snack',
    imgURL: '/cards/tail/fishsnack.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 105,
    name: 'gerbil',
    imgURL: '/cards/tail/gerbil.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 106,
    name: 'gila',
    imgURL: '/cards/tail/gila.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 107,
    name: 'granma\'s fan',
    imgURL: '/cards/tail/granmasfan.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [
      type.ATTACK,
      type.INNATE,
    ],
    energyCost: 1,
  },
  {
    id: 108,
    name: 'grass snake',
    imgURL: '/cards/tail/grasssnake.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 109,
    name: 'gravel ant',
    imgURL: '/cards/tail/gravelant.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 110,
    name: 'hare',
    imgURL: '/cards/tail/hare.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 111,
    name: 'hatsune',
    imgURL: '/cards/tail/hatsune.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 112,
    name: 'iguana',
    imgURL: '/cards/tail/iguana.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 113,
    name: 'koi',
    imgURL: '/cards/tail/koi.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 114,
    name: 'navaga',
    imgURL: '/cards/tail/navaga.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 115,
    name: 'nimo',
    imgURL: '/cards/tail/nimo.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [
      type.SKILL,
      type.BANISH,
    ],
    energyCost: 0,
  },
  {
    id: 116,
    name: 'nut cracker',
    imgURL: '/cards/tail/nutcrackertail.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 117,
    name: 'post fight',
    imgURL: '/cards/tail/postfight.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 118,
    name: 'potato leaf',
    imgURL: '/cards/tail/potatoleaf.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 119,
    name: 'pupae',
    imgURL: '/cards/tail/pupae.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 120,
    name: 'ranchu',
    imgURL: '/cards/tail/ranchu.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 121,
    name: 'rice',
    imgURL: '/cards/tail/rice.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 122,
    name: 'shiba',
    imgURL: '/cards/tail/shiba.png',
    class: axieClass.BEAST,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 2,
  },
  {
    id: 123,
    name: 'shrimp',
    imgURL: '/cards/tail/shrimp.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 124,
    name: 'snake jar',
    imgURL: '/cards/tail/snakejar.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.SECRET],
    energyCost: 1,
  },
  {
    id: 125,
    name: 'swallow',
    imgURL: '/cards/tail/swallow.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 126,
    name: 'tadpole',
    imgURL: '/cards/tail/tadpole.png',
    class: axieClass.AQUATIC,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 127,
    name: 'the last one',
    imgURL: '/cards/tail/thelastone.png',
    class: axieClass.BIRD,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 128,
    name: 'thorny caterpillar',
    imgURL: '/cards/tail/thornycaterpillar.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 129,
    name: 'tiny dino',
    imgURL: '/cards/tail/tinydino.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [
      type.ATTACK,
      type.RETAIN,
    ],
    energyCost: 1,
  },
  {
    id: 130,
    name: 'twin tail',
    imgURL: '/cards/tail/twintail.png',
    class: axieClass.BUG,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 131,
    name: 'wall gecko',
    imgURL: '/cards/tail/wallgecko.png',
    class: axieClass.REPTILE,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 1,
  },
  {
    id: 132,
    name: 'yam',
    imgURL: '/cards/tail/yam.png',
    class: axieClass.PLANT,
    part: parts.TAIL,
    type: [type.ATTACK],
    energyCost: 0,
  },
];